name: bonsai-preview
dependencies:
- python=3.7
- pip=19.1.1
- jupyter=1.0.0
- matplotlib=3.0.3
- seaborn=0.9.0
- plotly=3.10.0
- scipy=1.3.0
- pandas=0.25.1
- numpy=1.16.4
- pip:
  - microsoft-bonsai-api==0.1.2
  - bonsai-cli==1.0.5
  - vpython==7.6.0